---
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1
  
  vars_prompt:
  - name: "pw"
    prompt: "MOAR passwords"
    private: yes
  - name: "vm"
    prompt: "Enter a VM name"
    private: no
  - name: "mem"
    prompt: "Enter a Memory required in MB"
    private: no
  - name: "cpu"
    prompt: "Enter number CPUs required"
    private: no
  
  tasks:
   - vsphere_guest:
       vcenter_hostname: 10.10.10.19
       username: administrator@vsphere.local
       password: "{{pw}}"
       guest: "{{vm}}"
       state: reconfigured
       validate_certs: False
       vm_extra_config:
         vcpu.hotadd: yes
         mem.hotadd: yes
       vm_hardware:
         memory_mb: "{{mem}}"
         num_cpus: "{{cpu}}"
         osid: centos64Guest
         scsi: paravirtual
       esxi:
         datacenter: Datacenter
         hostname: 10.10.10.20
